name: Staging – App Engine Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: AppEngineDeploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Note GIT SHA as version
        id: version
        run: |
          echo "$GITHUB_SHA" > version.txt
        shell: bash
      - name: Deploy
        id: deploy
        uses: GoogleCloudPlatform/github-actions/appengine-deploy@master
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
      - name: Return URL
        id: deploy-complete
        run: echo "${{ steps.deploy.outputs.url }}"
